spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/lanchonete}
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        batch_fetch_style: dynamic
        default_batch_fetch_size: 16
        jdbc:
          batch_size: 16
          order_inserts: true
          order_updates: true

    show-sql: true
    generate-ddl: true

server:
  servlet:
    context-path: /lanchonete/api/v1

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

mercado-pago:
  enabled: true
  bearer-token: TEST-6374986705463106-012119-3af27c9e42cea21115c47aa04fabb992-208073926
  collector-id: 208073926
  pos-id: SUC001POSSUC001001