name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2
        with:
          dockerfile: Dockerfile
          context: .

      - name: Build Docker Image
        run: docker build -t your-docker-registry/your-image-name:latest .

      - name: Login to Docker Registry
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin your-docker-registry

      - name: Push Docker Image
        run: docker push your-docker-registry/your-image-name:latest

      - name: Setup AWS EKS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-aws-region

      - name: Configure kubectl
        run: aws eks update-kubeconfig --name your-eks-cluster-name

      - name: Deploy to EKS using Helm
        run: |
          helm upgrade --install \
            your-release-name \
            your-helm-chart-directory \
            --namespace your-namespace \
            --set image.repository=your-docker-registry/your-image-name \
            --set image.tag=latest
